### PR TITLE
Update docs to match the code regarding batch size

### PR DESCRIPTION
**Pull request by washingtoneg**
Adjusted to be in line with the README

### CODE REVIEW

**Comment by washingtoneg** [comment]
Fix for #6

**Comment by sgringwe** [comment]
@washingtoneg thanks for the PR! We actually changed it from 10k to 2k for performance reasons that we were noticing. We'd prefer to keep it at 2k, could you instead update the README to match the code?

**Comment by washingtoneg** [comment]
@sgringwe, thanks for reviewing! I made the change you requested in de32d36. Could you please elaborate on the performance issues you noticed? I'm curious and I'd like to use this code with as much context as you are willing to share.

Thanks for open sourcing this!

**Comment by sgringwe** [comment]
@washingtoneg thanks! I don't remember the exacts on the performance, unfortunately. can you look into the test failures?

**Comment by sgringwe** [comment]
@washingtoneg disreard the tests - your changes wouldn't have caused that

**Pull request merged**
